// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: mempoolapi/mempoolhist.proto

package mempoolapi

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TxidParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txid string `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"` // the txid
}

func (x *TxidParam) Reset() {
	*x = TxidParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mempoolapi_mempoolhist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxidParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxidParam) ProtoMessage() {}

func (x *TxidParam) ProtoReflect() protoreflect.Message {
	mi := &file_mempoolapi_mempoolhist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxidParam.ProtoReflect.Descriptor instead.
func (*TxidParam) Descriptor() ([]byte, []int) {
	return file_mempoolapi_mempoolhist_proto_rawDescGZIP(), []int{0}
}

func (x *TxidParam) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

type JsonResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Json string `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
}

func (x *JsonResp) Reset() {
	*x = JsonResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mempoolapi_mempoolhist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonResp) ProtoMessage() {}

func (x *JsonResp) ProtoReflect() protoreflect.Message {
	mi := &file_mempoolapi_mempoolhist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonResp.ProtoReflect.Descriptor instead.
func (*JsonResp) Descriptor() ([]byte, []int) {
	return file_mempoolapi_mempoolhist_proto_rawDescGZIP(), []int{1}
}

func (x *JsonResp) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type TimeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uts int64 `protobuf:"varint,1,opt,name=uts,proto3" json:"uts,omitempty"`
}

func (x *TimeResp) Reset() {
	*x = TimeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mempoolapi_mempoolhist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeResp) ProtoMessage() {}

func (x *TimeResp) ProtoReflect() protoreflect.Message {
	mi := &file_mempoolapi_mempoolhist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeResp.ProtoReflect.Descriptor instead.
func (*TimeResp) Descriptor() ([]byte, []int) {
	return file_mempoolapi_mempoolhist_proto_rawDescGZIP(), []int{2}
}

func (x *TimeResp) GetUts() int64 {
	if x != nil {
		return x.Uts
	}
	return 0
}

type TimerangeParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start int64 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	Stop  int64 `protobuf:"varint,2,opt,name=stop,proto3" json:"stop,omitempty"`
	Asc   bool  `protobuf:"varint,3,opt,name=asc,proto3" json:"asc,omitempty"`
}

func (x *TimerangeParam) Reset() {
	*x = TimerangeParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mempoolapi_mempoolhist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimerangeParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerangeParam) ProtoMessage() {}

func (x *TimerangeParam) ProtoReflect() protoreflect.Message {
	mi := &file_mempoolapi_mempoolhist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerangeParam.ProtoReflect.Descriptor instead.
func (*TimerangeParam) Descriptor() ([]byte, []int) {
	return file_mempoolapi_mempoolhist_proto_rawDescGZIP(), []int{3}
}

func (x *TimerangeParam) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *TimerangeParam) GetStop() int64 {
	if x != nil {
		return x.Stop
	}
	return 0
}

func (x *TimerangeParam) GetAsc() bool {
	if x != nil {
		return x.Asc
	}
	return false
}

type MemHist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uts  int64  `protobuf:"varint,1,opt,name=uts,proto3" json:"uts,omitempty"`
	Txid string `protobuf:"bytes,2,opt,name=txid,proto3" json:"txid,omitempty"` // the txid
}

func (x *MemHist) Reset() {
	*x = MemHist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mempoolapi_mempoolhist_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemHist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemHist) ProtoMessage() {}

func (x *MemHist) ProtoReflect() protoreflect.Message {
	mi := &file_mempoolapi_mempoolhist_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemHist.ProtoReflect.Descriptor instead.
func (*MemHist) Descriptor() ([]byte, []int) {
	return file_mempoolapi_mempoolhist_proto_rawDescGZIP(), []int{4}
}

func (x *MemHist) GetUts() int64 {
	if x != nil {
		return x.Uts
	}
	return 0
}

func (x *MemHist) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

type MemHistArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Memhist []*MemHist `protobuf:"bytes,1,rep,name=memhist,proto3" json:"memhist,omitempty"`
}

func (x *MemHistArray) Reset() {
	*x = MemHistArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mempoolapi_mempoolhist_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemHistArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemHistArray) ProtoMessage() {}

func (x *MemHistArray) ProtoReflect() protoreflect.Message {
	mi := &file_mempoolapi_mempoolhist_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemHistArray.ProtoReflect.Descriptor instead.
func (*MemHistArray) Descriptor() ([]byte, []int) {
	return file_mempoolapi_mempoolhist_proto_rawDescGZIP(), []int{5}
}

func (x *MemHistArray) GetMemhist() []*MemHist {
	if x != nil {
		return x.Memhist
	}
	return nil
}

var File_mempoolapi_mempoolhist_proto protoreflect.FileDescriptor

var file_mempoolapi_mempoolhist_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6d, 0x65, 0x6d, 0x70, 0x6f, 0x6f, 0x6c, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x65, 0x6d,
	0x70, 0x6f, 0x6f, 0x6c, 0x68, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x6d, 0x65, 0x6d, 0x70, 0x6f, 0x6f, 0x6c, 0x61, 0x70, 0x69, 0x22, 0x1f, 0x0a, 0x09, 0x54, 0x78,
	0x69, 0x64, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x69, 0x64, 0x22, 0x1e, 0x0a, 0x08, 0x4a,
	0x73, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x22, 0x1c, 0x0a, 0x08, 0x54,
	0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x74, 0x73, 0x22, 0x4c, 0x0a, 0x0e, 0x54, 0x69, 0x6d,
	0x65, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x73, 0x74, 0x6f, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x03, 0x61, 0x73, 0x63, 0x22, 0x2f, 0x0a, 0x07, 0x4d, 0x65, 0x6d, 0x48, 0x69,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x75, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x69, 0x64, 0x22, 0x3d, 0x0a, 0x0c, 0x4d, 0x65, 0x6d, 0x48,
	0x69, 0x73, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x2d, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x68,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x6d, 0x70,
	0x6f, 0x6f, 0x6c, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x6d, 0x48, 0x69, 0x73, 0x74, 0x52, 0x07,
	0x6d, 0x65, 0x6d, 0x68, 0x69, 0x73, 0x74, 0x32, 0xdb, 0x01, 0x0a, 0x0e, 0x4d, 0x65, 0x6d, 0x70,
	0x6f, 0x6f, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x15, 0x2e, 0x6d, 0x65, 0x6d, 0x70,
	0x6f, 0x6f, 0x6c, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x78, 0x69, 0x64, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x1a, 0x14, 0x2e, 0x6d, 0x65, 0x6d, 0x70, 0x6f, 0x6f, 0x6c, 0x61, 0x70, 0x69, 0x2e, 0x4a, 0x73,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x15, 0x2e, 0x6d, 0x65,
	0x6d, 0x70, 0x6f, 0x6f, 0x6c, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x78, 0x69, 0x64, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x1a, 0x14, 0x2e, 0x6d, 0x65, 0x6d, 0x70, 0x6f, 0x6f, 0x6c, 0x61, 0x70, 0x69, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0f, 0x46, 0x69,
	0x6e, 0x64, 0x4d, 0x65, 0x6d, 0x70, 0x6f, 0x6f, 0x6c, 0x68, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e,
	0x6d, 0x65, 0x6d, 0x70, 0x6f, 0x6f, 0x6c, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x72,
	0x61, 0x6e, 0x67, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x18, 0x2e, 0x6d, 0x65, 0x6d, 0x70,
	0x6f, 0x6f, 0x6c, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x6d, 0x48, 0x69, 0x73, 0x74, 0x41, 0x72,
	0x72, 0x61, 0x79, 0x22, 0x00, 0x42, 0x3c, 0x0a, 0x2c, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x68, 0x79, 0x70, 0x6f, 0x62, 0x61, 0x6c, 0x6c, 0x61, 0x64, 0x2e, 0x6d,
	0x65, 0x6d, 0x70, 0x6f, 0x6f, 0x6c, 0x68, 0x69, 0x73, 0x74, 0x2e, 0x6d, 0x65, 0x6d, 0x70, 0x6f,
	0x6f, 0x6c, 0x61, 0x70, 0x69, 0x42, 0x0a, 0x6d, 0x65, 0x6d, 0x70, 0x6f, 0x6f, 0x6c, 0x61, 0x70,
	0x69, 0x50, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mempoolapi_mempoolhist_proto_rawDescOnce sync.Once
	file_mempoolapi_mempoolhist_proto_rawDescData = file_mempoolapi_mempoolhist_proto_rawDesc
)

func file_mempoolapi_mempoolhist_proto_rawDescGZIP() []byte {
	file_mempoolapi_mempoolhist_proto_rawDescOnce.Do(func() {
		file_mempoolapi_mempoolhist_proto_rawDescData = protoimpl.X.CompressGZIP(file_mempoolapi_mempoolhist_proto_rawDescData)
	})
	return file_mempoolapi_mempoolhist_proto_rawDescData
}

var file_mempoolapi_mempoolhist_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_mempoolapi_mempoolhist_proto_goTypes = []interface{}{
	(*TxidParam)(nil),      // 0: mempoolapi.TxidParam
	(*JsonResp)(nil),       // 1: mempoolapi.JsonResp
	(*TimeResp)(nil),       // 2: mempoolapi.TimeResp
	(*TimerangeParam)(nil), // 3: mempoolapi.TimerangeParam
	(*MemHist)(nil),        // 4: mempoolapi.MemHist
	(*MemHistArray)(nil),   // 5: mempoolapi.MemHistArray
}
var file_mempoolapi_mempoolhist_proto_depIdxs = []int32{
	4, // 0: mempoolapi.MemHistArray.memhist:type_name -> mempoolapi.MemHist
	0, // 1: mempoolapi.MempoolService.GetMementry:input_type -> mempoolapi.TxidParam
	0, // 2: mempoolapi.MempoolService.GetMementryTime:input_type -> mempoolapi.TxidParam
	3, // 3: mempoolapi.MempoolService.FindMempoolhist:input_type -> mempoolapi.TimerangeParam
	1, // 4: mempoolapi.MempoolService.GetMementry:output_type -> mempoolapi.JsonResp
	2, // 5: mempoolapi.MempoolService.GetMementryTime:output_type -> mempoolapi.TimeResp
	5, // 6: mempoolapi.MempoolService.FindMempoolhist:output_type -> mempoolapi.MemHistArray
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mempoolapi_mempoolhist_proto_init() }
func file_mempoolapi_mempoolhist_proto_init() {
	if File_mempoolapi_mempoolhist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mempoolapi_mempoolhist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxidParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mempoolapi_mempoolhist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsonResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mempoolapi_mempoolhist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mempoolapi_mempoolhist_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimerangeParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mempoolapi_mempoolhist_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemHist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mempoolapi_mempoolhist_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemHistArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mempoolapi_mempoolhist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mempoolapi_mempoolhist_proto_goTypes,
		DependencyIndexes: file_mempoolapi_mempoolhist_proto_depIdxs,
		MessageInfos:      file_mempoolapi_mempoolhist_proto_msgTypes,
	}.Build()
	File_mempoolapi_mempoolhist_proto = out.File
	file_mempoolapi_mempoolhist_proto_rawDesc = nil
	file_mempoolapi_mempoolhist_proto_goTypes = nil
	file_mempoolapi_mempoolhist_proto_depIdxs = nil
}
